// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-y2078orq7jkOHYce7aaVvzgx1SruW3w',
    appId: '1:969179330277:web:d38a558e5d801ce36ac60c',
    messagingSenderId: '969179330277',
    projectId: 'task1-3a594',
    authDomain: 'task1-3a594.firebaseapp.com',
    storageBucket: 'task1-3a594.appspot.com',
    measurementId: 'G-WBJDD8065F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqF0aMyq2Ue5bYLhv6DYJ4woieMTGszR4',
    appId: '1:969179330277:android:c42a7268ed42fa076ac60c',
    messagingSenderId: '969179330277',
    projectId: 'task1-3a594',
    storageBucket: 'task1-3a594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6x80IZV1k6Mnj-Yq2AxZpJ7sJkKb9yA',
    appId: '1:969179330277:ios:a941047fc2dbc7e16ac60c',
    messagingSenderId: '969179330277',
    projectId: 'task1-3a594',
    storageBucket: 'task1-3a594.appspot.com',
    iosBundleId: 'com.example.task1',
  );

}